### PR TITLE
Create model version and schema migration

### PR DESCRIPTION
**Pull request by monidzik**
This PR allows us to add new columns to database.

However, it needs some preparation, and cannot be done automatically at once.

@daggarwa can you please follow my instructions below and test it first locally on our odb_test database, to make sure it works?
1. Manually add new table into existing database: 
You can use the following code:
```
CREATE TABLE schema_version (
  name VARCHAR(20) NOT NULL PRIMARY KEY,
  version BIGINT NOT NULL DEFAULT 1,
  migration BOOLEAN NOT NULL DEFAULT FALSE
);
INSERT INTO schema_version(name, version, migration)
VALUES ("", 1, FALSE);
```
(the easiest is to put this code into a file, then open Navicat and our odb_test database, you can right-click on `Tables`->`Execute_SQL_File` -> select the file and the new table will be created)
2. run the performance_test as it is in this branch
3. change #pragma db model version(1, 1) to #pragma db model version(1, 2) in **two** places: experiment_configuration.hpp line 44 and analysis_result.hpp line 85
4. uncomment line 165 in analysis_result.hpp (it will add new tables)
5. run the performance_test again
 
Let me know if it works, if so, we can merge this, run it, and then create new PR for points 3 and 4 from above.

---
This change is [Reviewable](https://reviewable.io/reviews/apexai/performance_test/112)

### CODE REVIEW

**Comment by daggarwa** [comment]
@monidzik ; I followed your instructions above and the approach seems to work . I was able to see the experiment data in DB preserved between the two performance test runs as attached here : 
[Exported_Query_Results.zip](https://github.com/ApexAI/performance_test/files/3785758/Exported_Query_Results.zip)

I could not see the new table created for versioning visually though in navicat. Is that something that MySQL rather maintains internally?

**Comment by daggarwa** [comment]
@monidzik One question. How do we plan to add the query for versioning for CI ?

**Review by daggarwa — COMMENTED** [review]
I am assigning it back to you for now

**Comment by monidzik** [comment]
> @monidzik ; I followed your instructions above and the approach seems to work . I was able to see the experiment data in DB preserved between the two performance test runs as attached here :
> [Exported_Query_Results.zip](https://github.com/ApexAI/performance_test/files/3785758/Exported_Query_Results.zip)
> 
> I could not see the new table created for versioning visually though in navicat. Is that something that MySQL rather maintains internally?

@daggarwa I can see in navicat the schema_version table, and it's the one that you created, cause I made sure I deleted it before assigning the review to you.

**Comment by monidzik** [comment]
> @monidzik One question. How do we plan to add the query for versioning for CI ?

@daggarwa I can create manually the schema_version table in the performance_results database (for example in Navicat, as I did for odb_test database) and then once this is merged, we can use master branch on CI. Then we will create a PR for making cpu_info (or any other new columns) not transient and we will set the version to 2 and again we can use the new master branch on CI. 

I'll maybe make the schema-version an argument we can provide to `ros2 run` or `colcon build`, and also add the version to the configuration table so we can keep track of it. What do you think?

**Comment by daggarwa** [comment]
> > @monidzik One question. How do we plan to add the query for versioning for CI ?
> 
> @daggarwa I can create manually the schema_version table in the performance_results database (for example in Navicat, as I did for odb_test database) and then once this is merged, we can use master branch on CI. Then we will create a PR for making cpu_info (or any other new columns) not transient and we will set the version to 2 and again we can use the new master branch on CI.
> 
> I'll maybe make the schema-version an argument we can provide to `ros2 run` or `colcon build`, and also add the version to the configuration table so we can keep track of it. What do you think?

For the model version . Do you have logic in the code that it gets automatically incremented by 1 ,whenever we would make changes to schema or do we have to provide a hard code for that value everytime?

**Comment by monidzik** [comment]
> For the model version . Do you have logic in the code that it gets automatically incremented by 1 ,whenever we would make changes to schema or do we have to provide a hard code for that value everytime?

No, I won't have logic for this, but I'll have schema version as cmake argument. We will have to update number when we update the code that change db schema. There is an option to block possibility of adding new variables if you don't update version, I think I'll set this, so in case we forget to update version, we will get a notification.

I will let you know when I have this ready to double check again if it works.

**Comment by jpsamper2009** [comment]
Moving this MR to Gitlab https://gitlab.com/ApexAI/performance_test/merge_requests/110. Closing this one.

**Pull request closed without merging**
