### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by esteve**
This updates the supported versions of ROS 2 and FastRTPS.

---
This change is [Reviewable](https://reviewable.io/reviews/apexai/performance_test/73)

### CODE REVIEW

**Comment by esteve** [comment]
@deeplearningrobotics can you have a look at these changes when you have a moment? Thanks.

**Comment by esteve** [comment]
Given that the change is very minor and that the current documentation is misleading since we claim to support Crystal and FastRTPS 1.7.0, I'm going to merge it anyway.

**Comment by deeplearningrobotics** [comment]
@esteve: Thanks a lot! Just saw your request now.

**Comment by esteve** [comment]
@deeplearningrobotics no problem, I forgot to update the README when I added support for Dashing and I noticed it was misleading our users, so merging without a review wasn't a big transgression :-)

**Pull request merged**
