### PR TITLE
Fix plotter edge cases

### PR DESCRIPTION
**Pull request by pbaughman**
* Fix perfplot not working if it's not in the same directory as the result file
* Give a better error message when someone gives `--skip-tail` or --skip-head` and a number that's larger than the amount of data that was captured
* Don't error-out when there's no data.  Generate empty plots instead
* Add an 'experiment status' line to the averages to indicate something failed with data collection when there's no data.

perfplot will generate something like the following when there's no data to plot
[bad_results.pdf](https://github.com/ApexAI/performance_test/files/3664202/bad_results.pdf)

Note that the `test setup` configuration on the left still shows information about the test, but there's no data to report.

---
This change is [Reviewable](https://reviewable.io/reviews/apexai/performance_test/91)

### CODE REVIEW

**Comment by pbaughman** [comment]
I almost forgot, I moved the max_rss plot from the left plot (which is all time stuff) to the right plot (which is all resource stuff)  Lyle and Andreas  were both fine with the change.

**Comment by daggarwa** [comment]
@pbaughman `perfplot` with argument `--skip-tail` or `--skip-head` doesn't give a correct usage message if I give it a negative number like let's say the following:
```bash
divya.aggarwal@ade:~/perf_test_ws/src/performance_test (fix_plotter_edge_cases u=)$ perfplot ~/perf_test_ws/log_Array1k_27-09-2019_14-32-04 --skip-head -100
Running tex for /home/divya.aggarwal/perf_test_ws/log_Array1k_27-09-2019_14-32-04
divya.aggarwal@ade:~/perf_test_ws/src/performance_test (fix_plotter_edge_cases u=)$ perfplot ~/perf_test_ws/log_Array1k_27-09-2019_14-32-04 --skip-tail -100
Running tex for /home/divya.aggarwal/perf_test_ws/log_Array1k_27-09-2019_14-32-04
```
Is this the intended behavior?

**Comment by pbaughman** [comment]
@daggarwa Probably not - what do you think it should do?  Print the help message?

**Comment by daggarwa** [comment]
> @daggarwa Probably not - what do you think it should do? Print the help message?

Yeah can give a similar message to what it gives for "out of bounds" row requests (basically number that's larger than the amount of data that was captured):
```
divya.aggarwal@ade:~/perf_test_ws/src/performance_test (fix_plotter_edge_cases u=)$ perfplot ~/perf_test_ws/log_Array1k_27-09-2019_14-32-04 --skip-tail 100
ERROR: Told to skip 0 rows from the start and 100 rows from the end but there are only 30 rows or data
```

**Comment by pbaughman** [comment]
@daggarwa done

**Comment by daggarwa** [comment]
> @daggarwa done

@pbaughman Looks good! I will approve the PR

**Pull request merged**
