### PR TITLE
Timer resolution

### PR DESCRIPTION
**Pull request by deeplearningrobotics**
This change is [Reviewable](https://reviewable.io/reviews/apexai/performance_test/11)

### CODE REVIEW

**Comment by serge-nikulin** [comment]
The changes look good.

Why did the checks fail?

**Comment by deeplearningrobotics** [comment]
@serge-nikulin: CI fails because I did not set it up properly yet.

**Comment by deeplearningrobotics** [comment]
@serge-nikulin: Can you approve please the code is ok?

**Comment by serge-nikulin** [comment]
@deeplearningrobotics, sorry, I don's see a big green "Approve" button anywhere. What should I do?

**Comment by deeplearningrobotics** [comment]
@serge-nikulin: Yes, thank you!

**Comment by hofucy** [comment]
Andrea Lea Medford

**Pull request merged**
