### PR TITLE
Plotter improvements

### PR DESCRIPTION
**Pull request by dejanpan**
This change is [Reviewable](https://reviewable.io/reviews/apexai/performance_test/49)

### CODE REVIEW

**Comment by deeplearningrobotics** [comment]
@durko: Could we rebase this on master?

**Comment by deeplearningrobotics** [comment]
@durko: Any updates on this?

**Comment by ltbj** [comment]
@deeplearningrobotics I'll be the one testing the changes against master. I expect to have this within the next week.

@durko FYI

**Comment by ltbj** [comment]
I validated the changes by running a handful of experiments and plotting the results. I'll attach a few for reference.

[log_Array1k_08-04-2019_23-09-36.pdf](https://github.com/ApexAI/performance_test/files/3057502/log_Array1k_08-04-2019_23-09-36.pdf)

[log_Array16k_08-04-2019_23-30-00.pdf](https://github.com/ApexAI/performance_test/files/3057504/log_Array16k_08-04-2019_23-30-00.pdf)

[log_Array16k_08-04-2019_23-32-23.pdf](https://github.com/ApexAI/performance_test/files/3057505/log_Array16k_08-04-2019_23-32-23.pdf)

[log_Array16k_08-04-2019_23-37-43.pdf](https://github.com/ApexAI/performance_test/files/3057508/log_Array16k_08-04-2019_23-37-43.pdf)

**Pull request merged**
