### PR TITLE
script to generate a report using both security on/off results

### PR DESCRIPTION
**Pull request by xabxx**
Users can view results in a single pdf file.

---
This change is [Reviewable](https://reviewable.io/reviews/apexai/performance_test/32)

### CODE REVIEW

**Comment by deeplearningrobotics** [comment]
@xabxx: We heavily refactored/updated the reporting tooling. Can you check if your improvements can be incorporated there: https://github.com/ApexAI/performance_test/tree/master/performance_test/helper_scripts/apex_performance_plotter

**Comment by xabxx** [comment]
@deeplearningrobotics I checked out the link and read the most recent README.md in master branch. I don't see a plotter script that does side-by-side comparison in a single perf report (which I am providing in this PR).

Could you take another look at this? 

Thanks!

**Comment by deeplearningrobotics** [comment]
@xabxx: Ok, the exact functionality was unclear to me. Can you please:

* Fix N = 17 as the number of rows to skip changed.
* Add a sentence to the README about what your plotter script does.

Then we can get it merged. Can you also run it to the ROS 2 python flake8 checker so that it does not fail CI if I try to import it?

Thank you!

**Comment by daggarwa** [comment]
The purpose of the PR is unclear and also the review comments are not addressed : https://github.com/ApexAI/performance_test/pull/32#issuecomment-476427713
So closing this for now.

**Pull request closed without merging**
